### ISSUE TITLE
Move to Module based Skeletoid, instead of Repo based 

### ISSUE THREAD

**Issue by neteinstein** [Mindera/skeletoid#55]
Have a single repo with all the skeletoid sub-sets and use a single module via gradle dependency.

https://android.jlelse.eu/publish-multi-module-android-libraries-on-jitpack-339213f6224c

**Comment by tallnato** [comment]
yes it is possible 😁

**Comment by neteinstein** [comment]
@tallnato Want to join the effort to change to this?

**Comment by tallnato** [comment]
Sure, but I will only be able to help after the end of next week 😰

I have it working here https://github.com/YouClap/RxFirebase

**Comment by neteinstein** [comment]
Attempt to address this on:
https://github.com/Mindera/skeletoid/pull/56

**Comment by tallnato** [comment]
Can we close this? we've done it in #61
